/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.UserDAO;

import javax.swing.JOptionPane;

import model.User;
import controller.Room;
import controller.Server;
import controller.ServerThread;

/**
 * @author Admin
 */
public class Admin extends javax.swing.JFrame implements Runnable {
    private final UserDAO userDAO;

    /**
     * Creates new form Admin
     */
    public Admin() {
        // Set a modern look-and-feel if Nimbus is available (safe, optional)
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // ignore and continue with default L&F
        }

        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        threadRoomListView.setEditable(false);
        messageView.setEditable(false);
        userDAO = new UserDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

         jScrollPane1 = new javax.swing.JScrollPane();
         threadRoomListView = new javax.swing.JTextArea();
         viewThreadButton = new javax.swing.JButton();
         viewRoomListButton = new javax.swing.JButton();
         jPanel1 = new javax.swing.JPanel();
         boardLabel = new javax.swing.JLabel();
         noticeTextField = new javax.swing.JTextField();
         publishMessageButton = new javax.swing.JButton();
         jScrollPane2 = new javax.swing.JScrollPane();
         messageView = new javax.swing.JTextArea();
         userIdTextField = new javax.swing.JTextField();
         banButton = new javax.swing.JButton();
         warnButton = new javax.swing.JButton();
         cancelBanButton = new javax.swing.JButton();
         reasonComboBox = new javax.swing.JComboBox<>();

         // Use dispose on close (constructor also sets it)
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

         // --- Header: darker bar with centered title ---
         jPanel1.setBackground(new java.awt.Color(32, 33, 36));
         jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
         boardLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22)); // NOI18N
         boardLabel.setForeground(new java.awt.Color(220, 220, 220));
         boardLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
         boardLabel.setText("Admin Panel — Caro Game Server");
         jPanel1.setLayout(new java.awt.BorderLayout());
         jPanel1.add(boardLabel, java.awt.BorderLayout.WEST);

         // --- Thread / Room list view (left) ---
         threadRoomListView.setColumns(20);
         threadRoomListView.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13)); // NOI18N
         threadRoomListView.setRows(5);
         threadRoomListView.setEditable(false);
         threadRoomListView.setBackground(new java.awt.Color(250, 250, 250));
         jScrollPane1.setViewportView(threadRoomListView);

         // --- Message view (right, top) ---
         messageView.setColumns(20);
         messageView.setRows(5);
         messageView.setEditable(false);
         messageView.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
         jScrollPane2.setViewportView(messageView);

         // --- Buttons and controls ---
         viewThreadButton.setText("Xem luồng");
         viewThreadButton.setFocusable(false);
         viewThreadButton.addActionListener((java.awt.event.ActionEvent evt) -> {
             viewThreadButtonActionPerformed(evt);
         });

         viewRoomListButton.setText("Xem phòng");
         viewRoomListButton.setFocusable(false);
         viewRoomListButton.addActionListener((java.awt.event.ActionEvent evt) -> {
             viewRoomListButtonActionPerformed(evt);
         });

         publishMessageButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // NOI18N
         publishMessageButton.setText("Phát thông báo");
         publishMessageButton.setFocusable(false);
         publishMessageButton.addActionListener((java.awt.event.ActionEvent evt) -> {
             publishMessageButtonActionPerformed(evt);
         });

         noticeTextField.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // NOI18N
         noticeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyPressed(java.awt.event.KeyEvent evt) {
                 noticeTextFieldKeyPressed(evt);
             }
         });

         banButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // NOI18N
         banButton.setText("Ban");
         banButton.setFocusable(false);
         banButton.addActionListener((java.awt.event.ActionEvent evt) -> {
             banButtonActionPerformed(evt);
         });

         warnButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // NOI18N
         warnButton.setText("Cảnh cáo");
         warnButton.setFocusable(false);
         warnButton.addActionListener((java.awt.event.ActionEvent evt) -> {
             warnButtonActionPerformed(evt);
         });

         cancelBanButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // NOI18N
         cancelBanButton.setText("Huỷ Ban");
         cancelBanButton.setFocusable(false);
         cancelBanButton.addActionListener((java.awt.event.ActionEvent evt) -> {
             cancelBanButtonActionPerformed(evt);
         });

         reasonComboBox.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13)); // NOI18N
         reasonComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Chọn lý do", "Spam", "Ngôn từ phản cảm", "Cố ý làm gián đoạn", "Sử dụng cheat", "Khác"}));

         // Build a refreshed main panel: horizontal split
         javax.swing.JPanel leftPanel = new javax.swing.JPanel(new java.awt.BorderLayout(6,6));
         leftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200,200,200)), "Danh sách luồng / phòng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14), new java.awt.Color(60,60,60)));
         leftPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

         javax.swing.JPanel rightPanel = new javax.swing.JPanel(new java.awt.BorderLayout(8,8));
         rightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200,200,200)), "Thông báo & Logs", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14), new java.awt.Color(60,60,60)));
         rightPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

         // Publish area below message view
         javax.swing.JPanel publishPanel = new javax.swing.JPanel(new java.awt.BorderLayout(6,6));
         noticeTextField.setColumns(1);
         publishPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6,6,6,6));
         publishPanel.add(noticeTextField, java.awt.BorderLayout.CENTER);
         publishPanel.add(publishMessageButton, java.awt.BorderLayout.EAST);
         rightPanel.add(publishPanel, java.awt.BorderLayout.SOUTH);

         // Compose split pane
         javax.swing.JSplitPane mainSplit = new javax.swing.JSplitPane(javax.swing.JSplitPane.HORIZONTAL_SPLIT, leftPanel, rightPanel);
         mainSplit.setResizeWeight(0.45);
         mainSplit.setDividerLocation(420);
         mainSplit.setBorder(null);

         // Bottom moderation controls
         javax.swing.JPanel bottomPanel = new javax.swing.JPanel();
         bottomPanel.setLayout(new javax.swing.BoxLayout(bottomPanel, javax.swing.BoxLayout.LINE_AXIS));
         bottomPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 12, 12));

         javax.swing.JPanel leftControls = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 6));
         leftControls.add(viewThreadButton);
         leftControls.add(viewRoomListButton);

         javax.swing.JPanel rightControls = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 6));
         rightControls.add(new javax.swing.JLabel("User ID:"));
         userIdTextField.setColumns(6);
         rightControls.add(userIdTextField);
         reasonComboBox.setPreferredSize(new java.awt.Dimension(260, 30));
         rightControls.add(reasonComboBox);
         rightControls.add(cancelBanButton);
         rightControls.add(warnButton);
         rightControls.add(banButton);

         bottomPanel.add(leftControls);
         bottomPanel.add(javax.swing.Box.createHorizontalGlue());
         bottomPanel.add(rightControls);

         // Main layout
         getContentPane().setLayout(new java.awt.BorderLayout(8,8));
         getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);
         getContentPane().add(mainSplit, java.awt.BorderLayout.CENTER);
         getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

         setPreferredSize(new java.awt.Dimension(900, 620));
         pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewThreadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewThreadButtonActionPerformed
        StringBuilder res = new StringBuilder();
        String room;
        int i = 1;
        for (ServerThread serverThread : Server.serverThreadBus.getListServerThreads()) {
            if (serverThread.getRoom() == null)
                room = null;
            else room = "" + serverThread.getRoom().getId();
            if (serverThread.getUser() != null) {
                res.append(i).append(". Client-number: ").append(serverThread.getClientNumber()).append(", User-ID: ").append(serverThread.getUser().getID()).append(", Room: ").append(room).append("\n");
            } else {
                res.append(i).append(". Client-number: ").append(serverThread.getClientNumber()).append(", User-ID: null, Room: ").append(room).append("\n");
            }
            i++;
        }
        threadRoomListView.setText(res.toString());
    }//GEN-LAST:event_viewThreadButtonActionPerformed

    private void viewRoomListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRoomListButtonActionPerformed
        StringBuilder res = new StringBuilder();
        int i = 1;
        for (ServerThread serverThread : Server.serverThreadBus.getListServerThreads()) {
            Room room1 = serverThread.getRoom();
            String listUser = "List user ID: ";
            if (room1 != null) {
                if (room1.getNumberOfUser() == 1) {
                    listUser += room1.getUser1().getUser().getID();
                } else {
                    listUser += room1.getUser1().getUser().getID() + ", " + room1.getUser2().getUser().getID();
                }
                res.append(i).append(". Room_ID: ").append(room1.getId()).append(", Number of player: ").append(room1.getNumberOfUser()).append(", ").append(listUser).append("\n");
                i++;
            }

        }
        threadRoomListView.setText(res.toString());
    }//GEN-LAST:event_viewRoomListButtonActionPerformed

    private void publishMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishMessageButtonActionPerformed
        sendMessage();
    }//GEN-LAST:event_publishMessageButtonActionPerformed

    private void noticeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noticeTextFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            sendMessage();
        }
    }//GEN-LAST:event_noticeTextFieldKeyPressed

    private void banButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banButtonActionPerformed
        try {
            if (isInvalidForm()) return;
            int userId = Integer.parseInt(userIdTextField.getText());
            User user = new User();
            user.setID(userId);
            userDAO.updateBannedStatus(user, true);
            ServerThread serverThread = Server.serverThreadBus.getServerThreadByUserID(userId);
            serverThread.write("banned-notice," + reasonComboBox.getSelectedItem());
            if (serverThread.getRoom() != null) {
                Room room = serverThread.getRoom();
                ServerThread competitorThread = room.getCompetitor(serverThread.getClientNumber());
                room.setUsersToNotPlaying();
                if (competitorThread != null) {
                    room.decreaseNumberOfGame();
                    competitorThread.write("left-room,");
                    competitorThread.setRoom(null);
                }
                serverThread.setRoom(null);
            }
            Server.admin.addMessage("User có ID " + userId + " đã bị BAN");
            serverThread.setUser(null);
            Server.serverThreadBus.boardCast(-1, "chat-server," + "User có ID " + userId + " đã bị BAN");
            JOptionPane.showMessageDialog(rootPane, "Đã BAN user " + userId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra");
        }
    }//GEN-LAST:event_banButtonActionPerformed

    private void cancelBanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBanButtonActionPerformed
        try {
            if (userIdTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập ID của User");
                return;
            }
            int userId = Integer.parseInt(userIdTextField.getText());
            User user = new User();
            user.setID(userId);
            userDAO.updateBannedStatus(user, false);
            userIdTextField.setText("");
            JOptionPane.showMessageDialog(rootPane, "Đã huỷ BAN user " + userId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra");
        }
    }//GEN-LAST:event_cancelBanButtonActionPerformed

    private void warnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnButtonActionPerformed
        try {
            if (isInvalidForm()) return;
            int userId = Integer.parseInt(userIdTextField.getText());
            Server.serverThreadBus.sendMessageToUserID(userId, "warning-notice," + reasonComboBox.getSelectedItem());
            JOptionPane.showMessageDialog(rootPane, "Đã cảnh cáo user " + userId);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra");
        }
    }//GEN-LAST:event_warnButtonActionPerformed

    private void sendMessage() {
        String message = noticeTextField.getText();
        if (message.isEmpty()) return;
        String temp = messageView.getText();
        temp += "Thông báo từ máy chủ : " + message + "\n";
        messageView.setText(temp);
        messageView.setCaretPosition(messageView.getDocument().getLength());
        Server.serverThreadBus.boardCast(-1, "chat-server,Thông báo từ máy chủ : " + message);
        noticeTextField.setText("");
    }

    public void addMessage(String message) {
        String tmp = messageView.getText();
        tmp = tmp + message + "\n";
        messageView.setText(tmp);
        messageView.setCaretPosition(threadRoomListView.getDocument().getLength());
    }

    private boolean isInvalidForm() {
        if (userIdTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập ID của User");
            return true;
        }
        if (reasonComboBox.getSelectedIndex() < 1) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn lý do");
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton banButton;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JButton cancelBanButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JTextArea messageView;
    private javax.swing.JTextField noticeTextField;
    private javax.swing.JButton publishMessageButton;
    private javax.swing.JComboBox<String> reasonComboBox;
    private javax.swing.JTextArea threadRoomListView;
    private javax.swing.JTextField userIdTextField;
    private javax.swing.JButton viewRoomListButton;
    private javax.swing.JButton viewThreadButton;
    private javax.swing.JButton warnButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        new Admin().setVisible(true);
    }
}

